version: '3'
services:
  nginx:
    image: nginx:1.13.7-alpine
    volumes:
     - ./config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
     - ./public:/usr/share/nginx/html/public
     - static:/usr/share/nginx/html/static
    ports:
     - "3000:3000"

  app:
    build: .
    ports:
     - "3001:3001"
    volumes:
     - .:/code
     - static:/code/static
volumes:
  static:
